In [2]:
# Import packages
import pandas as pd

In [3]:
# Memuat dataset ke dalam dataframe
df0 = pd.read_csv("/content/Divvy_Trips_2020_Q1.csv")

# Menampilkan beberapa baris pertama dari dataframe
df0.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,1068AB1B8F12FE23,docked_bike,1/1/2020 0:04,1/1/2020 0:17,Sheffield Ave & Wellington Ave,115,Ashland Ave & Belle Plaine Ave,246,41.9363,-87.6527,41.9561,-87.6688,casual,0:13:00,4
1,DCF74A0EB3284B3E,docked_bike,1/1/2020 0:10,1/1/2020 0:10,Daley Center Plaza,81,Daley Center Plaza,81,41.8842,-87.6296,41.8842,-87.6296,member,0:00:00,4
2,1C78B5F337CBFC93,docked_bike,1/1/2020 0:11,1/1/2020 0:13,Sheridan Rd & Irving Park Rd,240,Broadway & Sheridan Rd,256,41.9542,-87.6544,41.9528,-87.6500,member,0:02:00,4
3,4DE50A4FC7687A0D,docked_bike,1/1/2020 0:11,1/1/2020 0:15,Daley Center Plaza,81,Dearborn St & Van Buren St,624,41.8842,-87.6296,41.8763,-87.6292,member,0:04:00,4
4,D231CE7990A3AA52,docked_bike,1/1/2020 0:12,1/1/2020 0:14,Delano Ct & Roosevelt Rd,626,Wabash Ave & Roosevelt Rd,59,41.8675,-87.6322,41.8672,-87.6260,member,0:02:00,4

In [4]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426862 entries, 0 to 426861
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             426862 non-null  object
 1   rideable_type       426862 non-null  object
 2   started_at          426862 non-null  object
 3   ended_at            426862 non-null  object
 4   start_station_name  426862 non-null  object
 5   start_station_id    426862 non-null  int64
 6   end_station_name    426862 non-null  object
 7   end_station_id      426862 non-null  int64
 8   start_lat           426862 non-null  float64
 9   start_lng           426862 non-null  float64
 10  end_lat             426862 non-null  float64
 11  end_lng             426862 non-null  float64
 12  member_casual       426862 non-null  object
 13  ride_length         426862 non-null  object
 14  day_of_week         426862 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 48.9+ MB

In [5]:
df0.describe()

,start_station_id,end_station_id,start_lat,start_lng,end_lat,end_lng,day_of_week
count,426862.000000,426862.000000,426862.000000,426862.000000,426862.000000,426862.000000,426862.000000
mean,209.770553,209.311766,41.897847,-87.644155,41.897998,-87.644252,3.857418
std,163.188837,163.165359,0.038081,0.022665,0.038317,0.022661,1.835457
min,2.000000,2.000000,41.736600,-87.774700,41.736600,-87.774700,1.000000
25%,77.000000,77.000000,41.880300,-87.655000,41.880300,-87.655500,2.000000
50%,176.000000,175.000000,41.890600,-87.639900,41.890600,-87.640800,4.000000
75%,298.000000,297.000000,41.915700,-87.629500,41.916000,-87.629500,5.000000
max,675.000000,675.000000,42.064900,-87.549400,42.064900,-87.549400,7.000000

In [6]:
df0.isna().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
ride_length           0
day_of_week           0
dtype: int64

In [7]:
# Memeriksa apakah ada entri duplikat dalam data.
df0.duplicated().sum()

np.int64(0)