In [1]:
# Import packages
import pandas as pd

In [2]:
# Memuat dataset ke dalam dataframe
df0 = pd.read_csv("/content/Divvy_Trips_2019_Q1.csv")

# Menampilkan beberapa baris pertama dari dataframe
df0.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,ride_length,day_of_week
0,21742443,1/1/2019 0:04,1/1/2019 0:11,2167,390,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0,0:07:00,3
1,21742444,1/1/2019 0:08,1/1/2019 0:15,4386,441,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0,0:07:00,3
2,21742445,1/1/2019 0:13,1/1/2019 0:27,1524,829,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0,0:14:00,3
3,21742446,1/1/2019 0:13,1/1/2019 0:43,252,"1,783.00",123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0,0:30:00,3
4,21742447,1/1/2019 0:14,1/1/2019 0:20,1170,364,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0,0:06:00,3

In [3]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365069 entries, 0 to 365068
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            365069 non-null  int64
 1   start_time         365069 non-null  object
 2   end_time           365069 non-null  object
 3   bikeid             365069 non-null  int64
 4   tripduration       365069 non-null  object
 5   from_station_id    365069 non-null  int64
 6   from_station_name  365069 non-null  object
 7   to_station_id      365069 non-null  int64
 8   to_station_name    365069 non-null  object
 9   usertype           365069 non-null  object
 10  gender             345358 non-null  object
 11  birthyear          347046 non-null  float64
 12  ride_length        365069 non-null  object
 13  day_of_week        365069 non-null  int64
dtypes: float64(1), int64(5), object(8)
memory usage: 39.0+ MB

In [4]:
df0.describe()

,trip_id,bikeid,from_station_id,to_station_id,birthyear,day_of_week
count,3.650690e+05,365069.000000,365069.000000,365069.000000,347046.000000,365069.000000
mean,2.196087e+07,3429.484607,198.088816,198.581123,1981.674297,4.145460
std,1.271750e+05,1923.321025,153.493553,154.468304,11.245683,1.769965
min,2.174244e+07,1.000000,2.000000,2.000000,1900.000000,1.000000
25%,2.184876e+07,1777.000000,76.000000,76.000000,1975.000000,3.000000
50%,2.196183e+07,3489.000000,170.000000,168.000000,1985.000000,4.000000
75%,2.207182e+07,5157.000000,287.000000,287.000000,1990.000000,6.000000
max,2.217853e+07,6471.000000,665.000000,665.000000,2003.000000,7.000000

In [5]:
df0.isna().sum()

trip_id                  0
start_time               0
end_time                 0
bikeid                   0
tripduration             0
from_station_id          0
from_station_name        0
to_station_id            0
to_station_name          0
usertype                 0
gender               19711
birthyear            18023
ride_length              0
day_of_week              0
dtype: int64

In [6]:
# Memeriksa apakah ada entri duplikat dalam data.
df0.duplicated().sum()

np.int64(0)